FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-devel
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg git \
    && rm -rf /var/lib/apt/lists/*

COPY shared/ /app/shared/
COPY video/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY video/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
